services:
  latex:
    image: genjiohara/latex
    container_name: RLIME_paper-paper
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/root/workspace
      - ../experiments:/root/workspace/experiments
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    working_dir: /root/workspace
    tty: true
